server:
  port: 5050
  tomcat:
    uri-encoding: UTF-8

spring:
  http:
    encoding:
      charset: UTF-8
      force: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: xlaoy
      username: xlaoy
      password: ["1","2","3","4","5","6"]

swagger:
  docket:
    sso:
      title: SSO模块
      base-package: com.xlaoy.sso

#打开actuator的所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"